services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000/api
    depends_on:
      - backend
    networks:
      cinema:
        aliases:
          - frontend  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/cinema_db
      - JWT_SECRET=clavesupersecreta
      - TMDB_API_KEY=0bb80837f02e8a917a4622513bbe204f
      - TMDB_BASE_URL=https://api.themoviedb.org/3
      - TMDB_IMAGE_URL=https://image.tmdb.org/t/p
      - COOKIE_SECURE=true
      - GOOGLE_CLIENT_ID=642672677636-gu658qgu5b7u4rihifmgmp6sfbnhosdn.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - OAUTH_CALLBACK_URL=http://localhost:4000/api/auth/google/callback
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongodb
    networks:
      cinema:
        aliases:
          - backend  

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      cinema:
        aliases:
          - mongodb

  nginx: 
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      cinema:
        aliases:
          - nginx

volumes:
  mongodb_data: 

networks:
  cinema:
    driver: bridge
